# Generated by Django 6.0.7 on 2026-07-26 13:43

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_income'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='period_start',
            field=models.DateField(default=datetime.date(2026, 7, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='budget_cycle_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'period_start')},
        ),
    ]
